version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: programmeursdb
      MYSQL_USER: lfaria
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
